version: '3'
services:
  ingestion_service:
    image: registry.gitlab.com/datainsider/ingestion-service:1.4.15-nolake
    container_name: di-ingestion-service
    restart: always
    environment:
      NAME: ingestion-service
      MODE: production
      HTTP_PORT: 8489
      THRIFT_PORT: 8487
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs
networks:
  default:
    external:
      name: di_network
