version: "3.5"

services:
  ssdb:
    image: wendal/ssdb:latest
    container_name: di-ssdb
    #ports:
    #  - 8888:8888
    volumes:
      - ${PWD}/conf/ssdb.conf:/etc/ssdb.conf
      - ${PWD}/data/ssdb/data:/var/lib/ssdb/data
    restart: always


networks:
  default:
    external:
      name: di_network

