clickhouse_max_connection: 4096
clickhouse_path: /var/lib/clickhouse/
clickhouse_tmp_path: /var/lib/clickhouse/tmp/
clickhouse_user_files_path: /var/lib/clickhouse/user_files/
clickhouse_listen_host: 0.0.0.0
clickhouse_http_port: 8123
clickhouse_tcp_port: 9000
clickhouse_interserver_http_credentials_user: admin
clickhouse_interserver_http_credentials_password: pass4admin


mysql_host: di-mysql
mysql_port: 3306
mysql_username: root
mysql_password: di@2020!


#clickhouse_host: clickhouse01
#clickhouse_port: 8123
#clickhouse_username: default
#clickhouse_password: di@2020!
clickhouse_encryption_mode: aes-256-gcm
clickhouse_encryption_key: 2f17958458160187530dcdbdc0ce892fb67a18100733ec35b0f713a5790b765d
clickhouse_encryption_iv: d4fcb696b6e8e06b4a3cdc630e8176b7


ssdb_host: di-ssdb
ssdb_port: 8888


#TODO: zookeeper
#TODO: kafka


thrift_caas_host: di-user-profile
thrift_caas_port: 8589
thrift_schema_host: di-ingestion-service
thrift_schema_port: 8487
thrift_bi_host: di-bi-service
thrift_bi_port: 8084


api_key_resolver_default_key: c2c09332-14a1-4eb1-8964-2d85b2a561c8
api_key_resolver_username: root


tracking_client_host: http://di-event-tracking-mw:8080/tracking/warehouse/stream
tracking_client_api_key: c2c09332-14a1-4eb1-8964-2d85b2a561c8


sendgrid_api_key: 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
sendgrid_sender_email: sang@datainsider.co
sendgrid_sender_name: sender_name
