version: "3.5"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_home/conf.d/:/etc/nginx/conf.d/
      - ./nginx_home/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx_home/log/:/var/log/nginx/
      - ./nginx_home/html:/var/www/html/public
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
    restart: always


networks:
  default:
    external:
      name: di_network

