---
- name: Docker CE | Options | Add user {{ default_svc_user }}  to docker group
  user:
    name: "{{ default_svc_user }}"
    groups: docker
  ignore_errors: yes

- name: Docker CE | Options Create a network
  docker_network:
    name: "{{ docker_opts.network_name }}"
    enable_ipv6: no
    driver_options:
      com.docker.network.bridge.name: "{{ docker_opts.bridge_name }}"
    ipam_config:
      - subnet: "{{ docker_opts.subnet }}"
        gateway: "{{ docker_opts.gateway }}"
        iprange: "{{ docker_opts.iprange }}"
  when: docker_opts is defined

- name: Docker CE | Add credentials
  docker_login:
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email | default(omit) }}"
    config_path: "{{ item.config_path | default('~/.docker/config.json') }}"
    registry_url: "{{ item.registry_url | default('https://index.docker.io/v1/') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ docker_credentials }}"
  when: docker_credentials is defined
