version: '3'
services:
  bi_service:
    image: registry.gitlab.com/datainsider/bi-service:1.4.15
    container_name: di-bi-service
    restart: always
    environment:
      NAME: bi-service
      MODE: production
      HTTP_PORT: 8080
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs

networks:
  default:
    external:
      name: di_network
