version: '3.5'

services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper
    #ports:
    #  - 2181:2181
    #  - 2888:2888
    #  - 3888:3888
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/log:/datalog
    restart: always

networks:
  default:
    external:
      name: di_network
