---
# ansible_python_interpreter: /usr/bin/python3

svr_managed_domain: svr.localhost.localdomain
private_domain: localhost.localdomain

ntp1_ip: 1.debian.pool.ntp.org
ntp2_ip: 2.debian.pool.ntp.org

default_svc_user: devops

nameserver1_ip: 208.67.220.220
nameserver2_ip: 208.67.222.222
nameserver3_ip: 8.8.4.4

docker_opts:
  network_name: di_network
  bridge_name: bridge1
  subnet: "172.36.0.0/16"
  gateway: "172.36.0.1"
  iprange: "172.36.0.0/16"

sshd:
  sftp_only: 1
  group: devops

ulimit:
  nofile: 1024000
  noproc: 1024000
sysctl:
  net:
    netfilter:
      nf_conntrack_max: 30000000
    core:
      netdev_max_backlog: 262144
      somaxconn: 65535
      rmem_default: 131072
      rmem_max: 16777216
      wmem_max: 16777216
      dev_weight: 64
      opt_mem_max: 65536
    ipv4:
      tcp_max_syn_backlog: 262144
      tcp_syncookies: 1
      tcp_fin_timeout: 1
      tcp_tw_reuse: 1
      tcp_tw_recycle: 0
      tcp_max_orphans: 262144
      tcp_synack_retries: 2
      tcp_syn_retries: 2
      udp_rmem_min: 16384
      udp_wmem_min: 16384
      tcp_max_tw_buckets: 1440000
      tcp_mem: 65536 131072 262144
      udp_mem: 65536 131072 262144
      ip_nonlocal_bind: 0
      ip_local_reserved_ports: 4000-10000
      ip_forward: 1
    ipv6:
      conf:
        all:
          disable_ipv6: 1
  fs:
    file-max: 3000000
    nr_open: 3000000
  kernel:
    shmmax: 268435456
    shmall: 268435456
  vm:
    swappiness: 1
    dirty_ratio: 60
    dirty_background_ratio: 2
    overcommit_ratio: 0
    overcommit_memory: 0
    min_free_kbytes: 131072

docker_registry_url: "registry.gitlab.com"

docker_credentials:
  - { username: "gitlab+deploy-token-1337754", password: "aysJSVr_FBTSPoUUVygj", config_path: "/root/.docker/config.json", registry_url: "https://registry.gitlab.com" }
  - { username: "gitlab+deploy-token-1337754", password: "aysJSVr_FBTSPoUUVygj", config_path: "/home/devops/.docker/config.json", registry_url: "https://registry.gitlab.com" }
